# Use a lightweight Node.js image
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy only package.json and package-lock.json for faster caching in the root of the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Expose the development server port
EXPOSE 5173

# Install additional tools if needed (e.g., bash)
# RUN apk add --no-cache bash

# Set environment to development
ENV NODE_ENV=development

# Start the React development server
CMD ["npm", "run", "dev"]