/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package captureTheFlagConsola;

import Custom_CollectionsED.exceptions.EmptyCollectionException;
import captureTheFlagGame.*;
import captureTheFlagGame.Exceptions.NoSuchIndexException;
import captureTheFlagGame.GameFlow;
import captureTheFlagGame.Interfaces.GameFlowInterface;

import java.io.IOException;

public class App {
    public static void main(String[] args) {
        GameFlowInterface gameFlow = new GameFlow();

        try {
            gameFlow.startGame();
        } catch (EmptyCollectionException | IOException  | NoSuchIndexException e) {
            throw new RuntimeException(e.getMessage());
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
    }
}
