spring.application.name=Leaflings

zeebe.client.cloud.region=bru-2
zeebe.client.cloud.clusterId=dfdb8d36-5bf6-4b20-be42-8205ce0805f0
zeebe.client.cloud.clientId=YkutsuVxExA2Lp.IyAwJpI9.ks0HTV3q
zeebe.client.cloud.clientSecret=bN_TrP2-NbT8D6dCXQjI7IK.mCFe76mMDM0_FnUVI3-5oVtpfWbIBq6eDpJBzk4J
